### ISSUE TITLE
signald-cli exception

### ISSUE THREAD

**Issue by F0rth** [thefinn93/signald#10]
Hi,

When trying to use signald-cli, signald catch this:

12:26:35.754 [socketlistener] INFO  io.finn.signald.SocketHandler - Client connected
12:26:35.799 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
java.net.SocketException: Not open
        at org.newsclub.net.unix.AFUNIXSocketImpl.validFdOrException(AFUNIXSocketImpl.java:407) ~[junixsocket-common-2.2.0.jar:?]
        at org.newsclub.net.unix.AFUNIXSocketImpl.access$200(AFUNIXSocketImpl.java:46) ~[junixsocket-common-2.2.0.jar:?]
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:305) ~[junixsocket-common-2.2.0.jar:?]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:185) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
        at io.finn.signald.SocketHandler.run(SocketHandler.java:103) [signald.jar:unspecified]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by thefinn93** [comment]
To be clear, is `signald-cli` the golang project? Or signald and some other client?

**Comment by F0rth** [comment]
The golang project.

**Comment by thefinn93** [comment]
I don't think that project works very well, it was just something I was playing with. I assume it's crashing and improperly shutting down the socket here.

**Comment by F0rth** [comment]
Thx
