### ISSUE TITLE
Error registering user

### ISSUE THREAD

**Issue by ad-pro** [thefinn93/signald#8]
I have installed signald for debian, and tried to register phone number:
{"type": "register", "username": "+123456789"}
and got following error messate: 

{"type":"unexpected_error","data":{"msg_number":0,"message":"No password supplied for PKCS#12 KeyStore.","error":true,"request":{"type":"register","username","+123456789", ...

Any idea?

**Comment by ad-pro** [comment]
Looks like it was a problem of openjdk-11. Installed version 8, now it works

**Comment by thefinn93** [comment]
Thanks, good to know.

**Comment by skorokithakis** [comment]
Ah yes, I do have JDK 11 installed, I believe I updated recently.

**Comment by demure** [comment]
As a data point, I have signald working with `openjdk-11-jdk-headless` on debian sid (and that java 8 has been removed from sid).

**Comment by skorokithakis** [comment]
I downgraded to 8 and signald works fine.

**Comment by thefinn93** [comment]
I have pushed a change that I believe will fix this. Please pull master and try again. Go ahead and close this issue if it works.

**Comment by skorokithakis** [comment]
Hmm, no, now it doesn't work on JDK 8 either...

**Comment by skorokithakis** [comment]
No, sorry, it does work on 8. No dice on 11, unfortunately.

**Comment by thefinn93** [comment]
Interesting. It's working on Java 12 for me

**Comment by thefinn93** [comment]
does the same error as in the original issue occur on Java 11?

**Comment by skorokithakis** [comment]
Yes:

```
Apr 16 04:15:33 atlas signald[833]: 04:15:33.223 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
Apr 16 04:15:33 atlas signald[833]: java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore.
Apr 16 04:15:33 atlas signald[833]:         at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source) ~[bcprov-jdk15on-1.61.jar:1.61.0]
Apr 16 04:15:33 atlas signald[833]:         at java.security.KeyStore.load(KeyStore.java:1479) ~[?:?]
Apr 16 04:15:33 atlas signald[833]:         at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:367) ~[?:?]
Apr 16 04:15:33 atlas signald[833]:         at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:315) ~[?:?]
Apr 16 04:15:33 atlas signald[833]:         at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:59) ~[?:?]
Apr 16 04:15:33 atlas signald[833]:         at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:51) ~[?:?]
Apr 16 04:15:33 atlas signald[833]:         at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278) ~[?:?]
Apr 16 04:15:33 atlas signald[833]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAttachmentClient(PushServiceSocket.java:1093) ~[signal-service-java-2.13.0_unofficial_2.jar:?]
Apr 16 04:15:33 atlas signald[833]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.<init>(PushServiceSocket.java:155) ~[signal-service-java-2.13.0_unofficial_2.jar:?]
Apr 16 04:15:33 atlas signald[833]:         at org.whispersystems.signalservice.api.SignalServiceAccountManager.<init>(SignalServiceAccountManager.java:126) ~[signal-service-java-2.13.0_unofficial_2.jar:?]
Apr 16 04:15:33 atlas signald[833]:         at org.whispersystems.signalservice.api.SignalServiceAccountManager.<init>(SignalServiceAccountManager.java:102) ~[signal-service-java-2.13.0_unofficial_2.jar:?]
Apr 16 04:15:33 atlas signald[833]:         at io.finn.signald.Manager.init(Manager.java:271) ~[signald.jar:unspecified]
Apr 16 04:15:33 atlas signald[833]:         at io.finn.signald.SocketHandler.getManager(SocketHandler.java:303) ~[signald.jar:unspecified]
Apr 16 04:15:33 atlas signald[833]:         at io.finn.signald.SocketHandler.send(SocketHandler.java:198) ~[signald.jar:unspecified]
Apr 16 04:15:33 atlas signald[833]:         at io.finn.signald.SocketHandler.handleRequest(SocketHandler.java:134) [signald.jar:unspecified]
Apr 16 04:15:33 atlas signald[833]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:119) [signald.jar:unspecified]
Apr 16 04:15:33 atlas signald[833]:         at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by thefinn93** [comment]
I'm moving issues to GitLab. If this is still a problem (I don't believe it is, I've done better testing with Java 11 now) please refile it [here](https://gitlab.com/thefinn93/signald/issues/new).
